<?php
/**
 * Created by PhpStorm.
 * User: tuann
 * Date: 2/28/2019
 * Time: 22:40
 */

namespace app\modules\forum;

class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}